export const pastMeetings = [
  {
    id: 3,
    title: '마라톤 완주 도전',
    eventId: 6,
    eventTitle: '서울 마라톤',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-04-16 08:00',
    district: '중구',
    place: '광화문광장',
    participants: 5,
    maxPeople: 5,
    isHost: false,
  },
  {
    id: 4,
    title: '등산 모임',
    eventId: 7,
    eventTitle: '북한산 등산',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-03-12 09:00',
    district: '성북구',
    place: '북한산 입구',
    participants: 8,
    maxPeople: 10,
    isHost: true,
  },
  {
    id: 5,
    title: '요리 클래스',
    eventId: 8,
    eventTitle: '이탈리안 요리 배우기',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-02-20 15:00',
    district: '강남구',
    place: '쿠킹 스튜디오',
    participants: 6,
    maxPeople: 6,
    isHost: false,
  },
  {
    id: 6,
    title: '독서 토론 모임',
    eventId: 9,
    eventTitle: '베스트셀러 독서 토론',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-01-15 19:00',
    district: '서초구',
    place: '서초 도서관',
    participants: 10,
    maxPeople: 12,
    isHost: false,
  },
  {
    id: 7,
    title: '사진 촬영 워크숍',
    eventId: 10,
    eventTitle: '야경 사진 촬영',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-05-10 20:00',
    district: '용산구',
    place: '남산타워',
    participants: 7,
    maxPeople: 10,
    isHost: true,
  },
  {
    id: 8,
    title: '보드게임 모임',
    eventId: 11,
    eventTitle: '보드게임의 밤',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-04-05 18:00',
    district: '동대문구',
    place: '보드게임 카페',
    participants: 4,
    maxPeople: 8,
    isHost: false,
  },
  {
    id: 9,
    title: '요가 클래스',
    eventId: 12,
    eventTitle: '힐링 요가',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-03-25 10:00',
    district: '강동구',
    place: '요가 스튜디오',
    participants: 12,
    maxPeople: 15,
    isHost: true,
  },
  {
    id: 10,
    title: '캠핑 모임',
    eventId: 13,
    eventTitle: '가을 캠핑',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-10-15 14:00',
    district: '은평구',
    place: '캠핑장',
    participants: 6,
    maxPeople: 8,
    isHost: false,
  },
  {
    id: 11,
    title: '댄스 클래스',
    eventId: 14,
    eventTitle: '살사 댄스 배우기',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-06-20 19:00',
    district: '종로구',
    place: '댄스 스튜디오',
    participants: 10,
    maxPeople: 12,
    isHost: false,
  },
  {
    id: 12,
    title: '영화 감상 모임',
    eventId: 15,
    eventTitle: '고전 영화의 밤',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-07-15 20:00',
    district: '중구',
    place: '영화관',
    participants: 8,
    maxPeople: 10,
    isHost: true,
  },
  {
    id: 13,
    title: '런닝 모임',
    eventId: 16,
    eventTitle: '한강 러닝',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-08-10 06:00',
    district: '영등포구',
    place: '한강공원',
    participants: 15,
    maxPeople: 20,
    isHost: false,
  },
  {
    id: 14,
    title: '음악 감상 모임',
    eventId: 17,
    eventTitle: '클래식 음악의 밤',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-09-05 19:30',
    district: '서초구',
    place: '예술의 전당',
    participants: 9,
    maxPeople: 12,
    isHost: true,
  },
  {
    id: 15,
    title: '미술 전시 관람',
    eventId: 18,
    eventTitle: '현대 미술 전시',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-11-20 15:00',
    district: '종로구',
    place: '미술관',
    participants: 5,
    maxPeople: 8,
    isHost: false,
  },
  {
    id: 16,
    title: '테니스 모임',
    eventId: 19,
    eventTitle: '테니스 레슨',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-12-10 10:00',
    district: '송파구',
    place: '테니스 코트',
    participants: 6,
    maxPeople: 8,
    isHost: true,
  },
  {
    id: 17,
    title: '코딩 스터디',
    eventId: 20,
    eventTitle: '프론트엔드 개발',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-01-10 14:00',
    district: '강남구',
    place: '스터디 카페',
    participants: 10,
    maxPeople: 12,
    isHost: false,
  },
  {
    id: 18,
    title: '와인 시음회',
    eventId: 21,
    eventTitle: '와인과 치즈',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-02-14 18:00',
    district: '용산구',
    place: '와인 바',
    participants: 8,
    maxPeople: 10,
    isHost: true,
  },
  {
    id: 19,
    title: '플로깅 모임',
    eventId: 22,
    eventTitle: '환경을 위한 플로깅',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-03-18 07:00',
    district: '마포구',
    place: '홍대 거리',
    participants: 12,
    maxPeople: 15,
    isHost: false,
  },
  {
    id: 20,
    title: '게임 개발 워크숍',
    eventId: 23,
    eventTitle: 'Unity 게임 개발',
    eventImage: '/placeholder.svg?height=80&width=120',
    meetingTime: '2023-04-22 13:00',
    district: '성동구',
    place: 'IT 센터',
    participants: 10,
    maxPeople: 12,
    isHost: true,
  },
];
