name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Insecure Docker Repository
        run: |
          echo "{\"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY }}\"]}" | sudo tee /etc/docker/daemon.json > /dev/null
          sudo systemctl daemon-reload
          sudo systemctl restart docker

      - name: Build and push Docker image
        run: |
          docker build -t frontend .
          docker tag frontend ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 3000:3000 ${{ secrets.DOCKER_REGISTRY }}/frontend:latest